meta-ampere: meta-jade: update the hashed of default password
When users request power cycle via out-band IPMI commands, they might
see out-of-band IPMI commands fail in certain time. The issue is reproduced as
below.
Step 1:
ipmitool -H <BMCIP> -U root -P 0penBmc -C 17 -I lanplus chassis power cycle
 > Chassis Power Control: Cycle
Step 2:
ipmitool -H <BMCIP> -U root -P 0penBmc -C 17 -I lanplus chassis status
 > Error: no response from RAKP 1 message
 > Error: Received an Unexpected RAKP 2 message
 > Error: no response from RAKP 1 message
 > Error: Received an Unexpected RAKP 2 message
 > Error: no response from RAKP 1 message
 > Error: Received an Unexpected RAKP 2 message
 > Error: no response from RAKP 1 message
 > Get HPM.x Capabilities request failed, compcode = d4
 > Get Device ID command failed
 > No valid response received
 > Unable to get Chassis Power Status

Root cause: When users request out-band IPMI commands, BMC has to
execute PAM authenticate. BMC is using SHA512 algorithm to calculate
hashed value with default number of rounds (5000 times). But when users
request "power cycle", many tasks have been executed, therefore, CPU
does not have enough resource to completed calculation SHA512 on time,
it makes a timeout issue.

Solution: Update the salted of default password (0penBmc) to specific
number of rounds. The number of rounds is minimum value of SHA512
algorithmi (1000 times) to reduce SHA512 calculation time. The value is
generated from command 'openssl passwd -6 -salt rounds=1000\$UGMqyqdG 0penBmc'.

Tested:
	1. Request power cycle
           "ipmitool -H <BMCIP> -U root -P 0penBmc -C 17 -I
            lanplus chassis power cycle"
            > Chassis Power Control: Cycle
        2. Request read power status immediately
           "ipmitool -H <BMCIP> -U root -P 0penBmc -C 17 -I
            lanplus chassis status"
            > Chassis Power is on

Signed-off-by: Thang Tran <thuutran@amperecomputing.com>